[project]
name = "qcells-modbus-tools"
version = "0.2.0"
description = "Some python tools for QCells Q.VOLT P(5-15)T Inverter (SolarX Mic 3), modbus, mqtt, Shelly 3empro, Marstek Venus 3 and Home Assistant"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiomqtt==2.5.0",
    "pymodbus>=3.11.4",
    "pyserial>=3.5",
]
