  # taken from https://github.com/johann-CH/ESP32_DTSU666_Modbus_MQTT_HA_Integration
  # Smart Meter DTSU666 Converter States
  # changes:
  # - added more/all topics of my dtsu666
sensor:
  ...
  - name: 'DTSU666 Converter Modbus Errors 0xE0'
    unique_id: dtsu666_converter_modbus_errors_0xe0
    state_topic: 'DTSU666/Modbus/Diagnostic'
    icon: 'mdi:counter'
    value_template: '{{ value_json.DTSU666 }}'

  # Smart Meter DTSUU666
  - name: 'Smart Meter DTSU666 Voltage Phase A'
    unique_id: dtsu666_voltage_phase_a
    state_topic: 'DTSU666/Voltage_Phase_A'
    device_class: voltage
    unit_of_measurement: 'V'
    state_class: measurement
    value_template: '{{ value_json.Voltage_Phase_A }}'
    
  - name: 'Smart Meter DTSU666 Voltage Phase B'
    unique_id: dtsu666_voltage_phase_b
    state_topic: 'DTSU666/Voltage_Phase_B'
    device_class: voltage
    unit_of_measurement: 'V'
    state_class: measurement
    value_template: '{{ value_json.Voltage_Phase_B }}'
    
  - name: 'Smart Meter DTSU666 Voltage Phase C'
    unique_id: dtsu666_voltage_phase_c
    state_topic: 'DTSU666/Voltage_Phase_C'
    device_class: voltage
    unit_of_measurement: 'V'
    state_class: measurement
    value_template: '{{ value_json.Voltage_Phase_C }}'
    
  - name: 'Smart Meter DTSU666 Current Phase A'
    unique_id: dtsu666_current_phase_a
    state_topic: 'DTSU666/Current_Phase_A'
    device_class: current
    unit_of_measurement: 'A'
    state_class: measurement
    value_template: '{{ value_json.Current_Phase_A }}'
    
  - name: 'Smart Meter DTSU666 Current Phase B'
    unique_id: dtsu666_current_phase_b
    state_topic: 'DTSU666/Current_Phase_B'
    device_class: current
    unit_of_measurement: 'A'
    state_class: measurement
    value_template: '{{ value_json.Current_Phase_B }}'
    
  - name: 'Smart Meter DTSU666 Current Phase C'
    unique_id: dtsu666_current_phase_c
    state_topic: 'DTSU666/Current_Phase_C'
    device_class: current
    unit_of_measurement: 'A'
    state_class: measurement
    value_template: '{{ value_json.Current_Phase_C }}'
    
  - name: 'Smart Meter DTSU666 Total Active Power'
    unique_id: dtsu666_active_power
    state_topic: 'DTSU666/Total_Active_Power'
    device_class: power
    unit_of_measurement: 'kW'
    state_class: measurement
    force_update: true
    value_template: '{{ value_json.Total_Active_Power }}'
    
  - name: 'Smart Meter DTSU666 Active Power Phase A'
    unique_id: dtsu666_active_power
    state_topic: 'DTSU666/Active_Power_Phase_A'
    device_class: power
    unit_of_measurement: 'kW'
    state_class: measurement
    force_update: true
    value_template: '{{ value_json.Active_Power_Phase_A }}'

  - name: 'Smart Meter DTSU666 Active Power Phase B'
    unique_id: dtsu666_active_power
    state_topic: 'DTSU666/Active_Power_Phase_B'
    device_class: power
    unit_of_measurement: 'kW'
    state_class: measurement
    force_update: true
    value_template: '{{ value_json.Active_Power_Phase_B }}'

  - name: 'Smart Meter DTSU666 Active Power Phase C'
    unique_id: dtsu666_active_power
    state_topic: 'DTSU666/Active_Power_Phase_C'
    device_class: power
    unit_of_measurement: 'kW'
    state_class: measurement
    force_update: true
    value_template: '{{ value_json.Active_Power_Phase_C }}'

  - name: 'Smart Meter DTSU666 Total Reactive Power'
    unique_id: dtsu666_reactive_power
    state_topic: 'DTSU666/Total_Reactive_Power'
    device_class: power
    unit_of_measurement: 'kvar'
    state_class: measurement
    value_template: '{{ value_json.Total_Reactive_Power }}'
    
  - name: 'Smart Meter DTSU666 Reactive Power Phase A'
    unique_id: dtsu666_reactive_power
    state_topic: 'DTSU666/Reactive_Power_Phase_A'
    device_class: power
    unit_of_measurement: 'kvar'
    state_class: measurement
    value_template: '{{ value_json.Reactive_Power_Phase_A }}'

  - name: 'Smart Meter DTSU666 Reactive Power Phase B'
    unique_id: dtsu666_reactive_power
    state_topic: 'DTSU666/Reactive_Power_Phase_B'
    device_class: power
    unit_of_measurement: 'kvar'
    state_class: measurement
    value_template: '{{ value_json.Reactive_Power_Phase_B }}'

  - name: 'Smart Meter DTSU666 Reactive Power Phase C'
    unique_id: dtsu666_reactive_power
    state_topic: 'DTSU666/Reactive_Power_Phase_C'
    device_class: power
    unit_of_measurement: 'kvar'
    state_class: measurement
    value_template: '{{ value_json.Reactive_Power_Phase_C }}'

  - name: 'Smart Meter DTSU666 Total Power Factor'
    unique_id: dtsu666_power_factor
    state_topic: 'DTSU666/Total_Power_Factor'
    device_class: power_factor
    state_class: measurement
    value_template: '{{ value_json.Total_Power_Factor }}'
    
  - name: 'Smart Meter DTSU666 Power Factor Phase A'
    unique_id: dtsu666_power_factor
    state_topic: 'DTSU666/Power_Factor_Phase_A'
    device_class: power_factor
    state_class: measurement
    value_template: '{{ value_json.Power_Factor_Phase_A }}'

  - name: 'Smart Meter DTSU666 Power Factor Phase B'
    unique_id: dtsu666_power_factor
    state_topic: 'DTSU666/Power_Factor_Phase_B'
    device_class: power_factor
    state_class: measurement
    value_template: '{{ value_json.Power_Factor_Phase_B }}'

  - name: 'Smart Meter DTSU666 Power Factor Phase C'
    unique_id: dtsu666_power_factor
    state_topic: 'DTSU666/Power_Factor_Phase_C'
    device_class: power_factor
    state_class: measurement
    value_template: '{{ value_json.Power_Factor_Phase_C }}'

  - name: 'Smart Meter DTSU666 Frequency'
    unique_id: dtsu666_frequency
    state_topic: 'DTSU666/Frequency'
    device_class: frequency
    unit_of_measurement: 'Hz'
    state_class: measurement
    value_template: '{{ value_json.Frequency }}'
    
  - name: 'Smart Meter DTSU666 Total Import Energy'
    unique_id: dtsu666_import_energy_total
    state_topic: 'DTSU666/Total_Import_Energy'
    device_class: energy
    unit_of_measurement: 'kWh'
    state_class: measurement
    force_update: true
    value_template: '{{ value_json.Total_Import_Energy }}'

  - name: 'Smart Meter DTSU666 Import Energy Phase A'
    unique_id: dtsu666_import_energy_total
    state_topic: 'DTSU666/Import_Energy_A'
    device_class: energy
    unit_of_measurement: 'kWh'
    state_class: measurement
    force_update: true
    value_template: '{{ value_json.Import_Energy_A }}'

  - name: 'Smart Meter DTSU666 Import Energy Phase B'
    unique_id: dtsu666_import_energy_total
    state_topic: 'DTSU666/Import_Energy_B'
    device_class: energy
    unit_of_measurement: 'kWh'
    state_class: measurement
    force_update: true
    value_template: '{{ value_json.Import_Energy_B }}'

  - name: 'Smart Meter DTSU666 Import Energy Phase C'
    unique_id: dtsu666_import_energy_total
    state_topic: 'DTSU666/Import_Energy_C'
    device_class: energy
    unit_of_measurement: 'kWh'
    state_class: measurement
    force_update: true
    value_template: '{{ value_json.Import_Energy_C }}'

  - name: 'Smart Meter DTSU666 Total Net Import Energy'
    unique_id: dtsu666_import_energy_total
    state_topic: 'DTSU666/Total_Net_Import_Energy'
    device_class: energy
    unit_of_measurement: 'kWh'
    state_class: measurement
    force_update: true
    value_template: '{{ value_json.Total_Net_Import_Energy }}'

  - name: 'Smart Meter DTSU666 Total Export Energy'
    unique_id: dtsu666_export_energy_total
    state_topic: 'DTSU666/Total_Export_Energy'
    device_class: energy
    unit_of_measurement: 'kWh'
    state_class: measurement
    force_update: true
    value_template: '{{ value_json.Total_Export_Energy }}'

  - name: 'Smart Meter DTSU666 Export Energy Phase A'
    unique_id: dtsu666_export_energy_total
    state_topic: 'DTSU666/Export_Energy_A'
    device_class: energy
    unit_of_measurement: 'kWh'
    state_class: measurement
    force_update: true
    value_template: '{{ value_json.Export_Energy_A }}'

  - name: 'Smart Meter DTSU666 Export Energy Phase B'
    unique_id: dtsu666_export_energy_total
    state_topic: 'DTSU666/Export_Energy_B'
    device_class: energy
    unit_of_measurement: 'kWh'
    state_class: measurement
    force_update: true
    value_template: '{{ value_json.Export_Energy_B }}'

  - name: 'Smart Meter DTSU666 Export Energy Phase C'
    unique_id: dtsu666_export_energy_total
    state_topic: 'DTSU666/Export_Energy_C'
    device_class: energy
    unit_of_measurement: 'kWh'
    state_class: measurement
    force_update: true
    value_template: '{{ value_json.Export_Energy_C }}'

  - name: 'Smart Meter DTSU666 Total Net Export Energy'
    unique_id: dtsu666_export_energy_total
    state_topic: 'DTSU666/Total_Net_Export_Energy'
    device_class: energy
    unit_of_measurement: 'kWh'
    state_class: measurement
    force_update: true
    value_template: '{{ value_json.Total_Net_Export_Energy }}'

  ...

#EOF